Repository konkuk-PlaceList/PlaceList, pull requests merged in 2023-06, with the labels that each got.

#12 feat: UI 구현(1) 및 Places RecyclerView Adapter 작성
  app/src/main/java/org/konkuk/placelist/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/AddPlaceListener.kt
  app/src/main/java/org/konkuk/placelist/IntroActivity.kt
  app/src/main/java/org/konkuk/placelist/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/MapFragment.kt
  app/src/main/java/org/konkuk/placelist/MyViewModel.kt
  app/src/main/java/org/konkuk/placelist/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/domain/Place.kt
  app/src/main/java/org/konkuk/placelist/domain/enums/Coordinate.kt
  app/src/main/res/anim/splash_translate.xml
  app/src/main/res/drawable-v24/img_p.png
  app/src/main/res/drawable/ic_search_gray.xml
  app/src/main/res/drawable/search_resize.xml
  app/src/main/res/layout/activity_places.xml
  app/src/main/res/layout/activity_todo.xml
  app/src/main/res/layout/fragment_add_place.xml
  app/src/main/res/layout/fragment_add_todo.xml
  app/src/main/res/layout/fragment_set_time.xml
Labels: 기능 구현 🛫, UI 구성 ✨

#15 feat: Room 도입, Todo까지의 UI 구현
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/konkuk/placelist/AddTodoFragment.kt
  app/src/main/java/org/konkuk/placelist/Database.kt
  app/src/main/java/org/konkuk/placelist/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/dao/Converters.kt
  app/src/main/java/org/konkuk/placelist/dao/PlacesDao.kt
  app/src/main/java/org/konkuk/placelist/dao/TodoDao.kt
  app/src/main/java/org/konkuk/placelist/domain/Place.kt
  app/src/main/java/org/konkuk/placelist/domain/Subtask.kt
  app/src/main/java/org/konkuk/placelist/domain/Task.kt
  app/src/main/java/org/konkuk/placelist/domain/Todo.kt
  app/src/main/java/org/konkuk/placelist/intro/IntroActivity.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceListener.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
  app/src/main/java/org/konkuk/placelist/main/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoListener.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
  app/src/main/res/drawable/repeat_onoff.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_places.xml
  app/src/main/res/layout/activity_todo.xml
  app/src/main/res/layout/fragment_add_place.xml
  app/src/main/res/layout/fragment_add_todo.xml
  app/src/main/res/layout/fragment_map.xml
Labels: 기능 구현 🛫, 리팩터링 🛠, UI 구성 ✨

#16 feat: recyclerView Swipe delete 구현
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
Labels: 기능 구현 🛫

#19 feat: 환경 설정 기능 추가, Preference 사용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/setting/SetTimeDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/setting/SettingsActivity.kt
  app/src/main/res/drawable/baseline_settings_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_set_time.xml
  app/src/main/res/layout/settings_activity.xml
  app/src/main/res/xml/root_preferences.xml
Labels: 기능 구현 🛫, UI 구성 ✨, 알림 기능 🔔

#20 Refactor: 메인 화면 ConstraintLayout에서 LinearLayout으로 수정, 통일성 유지
  app/src/main/res/layout/activity_main.xml
Labels: 리팩터링 🛠, UI 구성 ✨

#18 feat: 핀 범위 설정 기능 추가
  app/src/main/java/org/konkuk/placelist/MyViewModel.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceListener.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
  app/src/main/java/org/konkuk/placelist/main/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
  app/src/main/res/drawable/thumb_img.xml
  app/src/main/res/layout/fragment_add_place.xml
  app/src/main/res/layout/places_row.xml
Labels: 기능 구현 🛫, UI 구성 ✨

#21 feat: 장소 수정 기능 추가
  app/build.gradle
  app/src/main/java/org/konkuk/placelist/TodoActivity.kt
  app/src/main/java/org/konkuk/placelist/domain/Place.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceListener.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
  app/src/main/java/org/konkuk/placelist/main/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/res/drawable/check_resize.xml
  app/src/main/res/layout/activity_places.xml
  app/src/main/res/layout/activity_todo.xml
  app/src/main/res/layout/fragment_add_place.xml
  app/src/main/res/layout/fragment_add_todo.xml
Labels: 기능 구현 🛫

#25 feat: Todo 반복 요일 추가, 장소 삭제 시 전체 삭제 (알림 창 구현)
  app/src/main/java/org/konkuk/placelist/domain/Todo.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
Labels: 기능 구현 🛫

#27 fix: 버그 수정 및 다크모드 해제
  app/src/main/java/org/konkuk/placelist/intro/IntroActivity.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
Labels: 심각한 버그 🐛, UI 구성 ✨

#26 확대 후 위치 재선정시 축소되는 것 수정
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
Labels: 기능 구현 🛫, 리팩터링 🛠

#24 feat: 날씨 알림 받기 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/setting/SetTimeDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/setting/SettingsActivity.kt
  app/src/main/java/org/konkuk/placelist/weather/Repository.kt
  app/src/main/java/org/konkuk/placelist/weather/WeatherAlarmReceiver.kt
  app/src/main/java/org/konkuk/placelist/weather/models/airquality/AirQualityResponse.kt
  app/src/main/java/org/konkuk/placelist/weather/models/airquality/Body.kt
  app/src/main/java/org/konkuk/placelist/weather/models/airquality/Grade.kt
  app/src/main/java/org/konkuk/placelist/weather/models/airquality/Header.kt
  app/src/main/java/org/konkuk/placelist/weather/models/airquality/MeasuredValue.kt
  app/src/main/java/org/konkuk/placelist/weather/models/airquality/Response.kt
  app/src/main/java/org/konkuk/placelist/weather/models/monitoringstation/Body.kt
  app/src/main/java/org/konkuk/placelist/weather/models/monitoringstation/Header.kt
  app/src/main/java/org/konkuk/placelist/weather/models/monitoringstation/MonitoringStation.kt
  app/src/main/java/org/konkuk/placelist/weather/models/monitoringstation/MonitoringStationsResponse.kt
  app/src/main/java/org/konkuk/placelist/weather/models/monitoringstation/Response.kt
  app/src/main/java/org/konkuk/placelist/weather/models/tmcoordinates/Document.kt
  app/src/main/java/org/konkuk/placelist/weather/models/tmcoordinates/Meta.kt
  app/src/main/java/org/konkuk/placelist/weather/models/tmcoordinates/TmCoordinatesResponse.kt
  app/src/main/java/org/konkuk/placelist/weather/models/weatherforecast/Body.kt
  app/src/main/java/org/konkuk/placelist/weather/models/weatherforecast/Header.kt
  app/src/main/java/org/konkuk/placelist/weather/models/weatherforecast/Response.kt
  app/src/main/java/org/konkuk/placelist/weather/models/weatherforecast/WeatherForecast.kt
  app/src/main/java/org/konkuk/placelist/weather/models/weatherforecast/WeatherForecastResponse.kt
  app/src/main/java/org/konkuk/placelist/weather/models/weatherforecast/WeatherForecasts.kt
  app/src/main/java/org/konkuk/placelist/weather/object/GpsConverter.kt
  app/src/main/java/org/konkuk/placelist/weather/object/Url.kt
  app/src/main/java/org/konkuk/placelist/weather/services/AirKoreaApiService.kt
  app/src/main/java/org/konkuk/placelist/weather/services/KakaoLocalApiService.kt
  app/src/main/java/org/konkuk/placelist/weather/services/KmaApiService.kt
  app/src/main/res/drawable/baseline_alarm_24.xml
  app/src/main/res/xml/root_preferences.xml
Labels: 기능 구현 🛫, 알림 기능 🔔

#28 feat: 스플래시 애니메이션 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/konkuk/placelist/intro/IntroActivity.kt
  app/src/main/res/anim/splash_translate.xml
  app/src/main/res/drawable-v24/btn_settings.png
  app/src/main/res/drawable-v24/logo_placelist.png
  app/src/main/res/drawable/baseline_settings_24.xml
  app/src/main/res/drawable/ic_search_gray.xml
  app/src/main/res/drawable/img_lacelist.xml
  app/src/main/res/drawable/img_p_vector.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_todo.xml
  app/src/main/res/values/styles.xml
Labels: 기능 구현 🛫, UI 구성 ✨

#30 refactor: Geofence 수정사항 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/konkuk/placelist/GeofenceBroadcastReceiver.kt
  app/src/main/java/org/konkuk/placelist/MyGeofence.kt
  app/src/main/java/org/konkuk/placelist/dao/PlacesDao.kt
  app/src/main/java/org/konkuk/placelist/dao/TodoDao.kt
  app/src/main/java/org/konkuk/placelist/domain/Place.kt
  app/src/main/java/org/konkuk/placelist/domain/Todo.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceListener.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoListener.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
Labels: 기능 구현 🛫, 리팩터링 🛠

#29 feat: Todo 체크 기능 추가
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
  app/src/main/res/layout/todo_row.xml
Labels: 기능 구현 🛫

#32 refactor: 카메라 이동 자연스럽게 구현
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
Labels: 리팩터링 🛠

#31 feat: 스와이프 시 뒷배경 추가
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/res/layout/places_row.xml
  app/src/main/res/layout/todo_row.xml
Labels: 기능 구현 🛫, UI 구성 ✨

#34 refactor: API 31 지원
  app/src/main/java/org/konkuk/placelist/domain/Subtask.kt
  app/src/main/java/org/konkuk/placelist/domain/Task.kt
  app/src/main/java/org/konkuk/placelist/domain/enums/NotificationType.kt
  app/src/main/java/org/konkuk/placelist/intro/IntroActivity.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
Labels: 리팩터링 🛠

#23 feat: geofence 알림 구현
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/konkuk/placelist/GeofenceBroadcastReceiver.kt
  app/src/main/java/org/konkuk/placelist/MyGeofence.kt
  app/src/main/java/org/konkuk/placelist/dao/PlacesDao.kt
  app/src/main/java/org/konkuk/placelist/dao/TodoDao.kt
  app/src/main/java/org/konkuk/placelist/domain/Place.kt
  app/src/main/java/org/konkuk/placelist/domain/Todo.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceListener.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/PlaceAdapter.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoListener.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/place/TodoAdapter.kt
Labels: 기능 구현 🛫, 알림 기능 🔔, 높은 우선순위 🔺

#35 refactor: 리팩터링
  app/src/main/java/org/konkuk/placelist/GeofenceBroadcastReceiver.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/main/MapFragment.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/weather/Repository.kt
  app/src/main/java/org/konkuk/placelist/weather/WeatherAlarmReceiver.kt
  app/src/main/res/layout/fragment_add_todo.xml
  app/src/main/res/values/strings.xml
Labels: 리팩터링 🛠, UI 구성 ✨

#38 이상한 주소 입력 시 오류
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
Labels: 심각한 버그 🐛

#36 design: UI 리스트 간격 수정, 로고 이미지 크기 수정
  app/src/main/java/org/konkuk/placelist/GeofenceBroadcastReceiver.kt
  app/src/main/java/org/konkuk/placelist/main/AddPlaceDialogFragment.kt
  app/src/main/java/org/konkuk/placelist/place/AddTodoDialogFragment.kt
  app/src/main/res/drawable-v24/btn_settings.png
  app/src/main/res/drawable-v24/logo_placelist.png
  app/src/main/res/drawable/logo_placelist_vector.xml
  app/src/main/res/layout/fragment_add_place.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/places_row.xml
  app/src/main/res/values/strings.xml
Labels: UI 구성 ✨

#37 refactor: 알림 형식 변경 (Inbox), Todo 알림 클릭 시 해당 Place로 이동
  app/src/main/java/org/konkuk/placelist/GeofenceBroadcastReceiver.kt
  app/src/main/java/org/konkuk/placelist/MyGeofence.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/weather/WeatherAlarmReceiver.kt
  app/src/main/res/layout/fragment_add_todo.xml
Labels: 기능 구현 🛫, 리팩터링 🛠, UI 구성 ✨

#40 feat: 항목이 없을 경우 힌트 텍스트 구현
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_places.xml
Labels: 기능 구현 🛫, UI 구성 ✨

#41 Develop fix design
  app/src/main/java/org/konkuk/placelist/GeofenceBroadcastReceiver.kt
  app/src/main/java/org/konkuk/placelist/main/MainActivity.kt
  app/src/main/java/org/konkuk/placelist/place/PlacesActivity.kt
  app/src/main/java/org/konkuk/placelist/weather/WeatherAlarmReceiver.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/places_row.xml
  app/src/main/res/layout/todo_row.xml
Labels: 리팩터링 🛠, UI 구성 ✨
